<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php if ($firstname != null): ?>
        <p>Hello <?=htmlspecialchars($firstname);?> !</p>
    <?php endif; ?>

    <?php 
    // if ($firstname != null) { 
    //     echo "<p>Salut $firstname !</p>";
    // } 
    ?>

    <form action="index.php" method="GET">
        <fieldset>
            <legend>Formulaire de test</legend>
            <div>
                <label for="firstname">Prénom</label>
                <input type="text" name="firstname" id="firstname" placeholder="Votre prénom ici">
            </div>
            <input type="submit" value="Envoyer">
        </fieldset>
    </form>
</body>
</html>