<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>Loto</h1>
    </header>
    <main>
        <ul>
            <?php foreach ($tirage as $number) { ?>
                <li><?php echo $number;?></li>
            <?php } ?>
        </ul>

        <ul>
            <!-- Version avec la syntaxe alternative : + endforeach à la place des accolades -->
            <?php foreach ($tirage as $number) : ?>
                <li><?=$number;?></li> <!-- <?=$number;?> équivaut à <?php echo $number;?> -->
            <?php endforeach; ?>
        </ul>
    </main>
</body>
</html>