<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <h1><?=htmlspecialchars($pageTitle ?? 'Accueil');?></h1>
        <nav>
            <a href="index.php">Accueil</a>
            <a href="add-product.php">Ajouter un produit</a>
            <a href="products.php">Tous les produits</a>
        </nav>
    </header>