<!-- CODE HTML DU FORMULAIRE --> 

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODOLIST</title>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
</head>

<body>
    <section class="vh-100 gradient-custom-2">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-12 col-xl-10">
                    <div class="mask-custom">
                        <div class="card-body p-4 text-white">

                            <form action="addTask.php" method="POST">
                                <fieldset>
                                    <legend>Ajout d'une nouvelle tâche</legend>
                                    <div class="mb-3 form-group">
                                        <label for="title">Titre</label>
                                        <input value="<?=htmlspecialchars($title);?>" type="text" name="title" class="form-control" id="title" placeholder="Titre de la tâche">
                                        <?php if (isset($errors['title'])): ?>
                                            <p class="mt-3 alert alert-danger"><?=htmlspecialchars($errors['title']);?></p>
                                        <?php endif; ?>
                                    </div>
                                    <div class="mb-3 form-group">
                                        <label for="description">Description</label>
                                        <textarea rows="3" name="description" class="form-control" id="description"><?=htmlspecialchars($description);?></textarea>
                                        <?php if (isset($errors['description'])): ?>
                                            <p class="mt-3 alert alert-danger"><?=htmlspecialchars($errors['description']);?></p>
                                        <?php endif; ?>
                                    </div>
                                    <div class="mb-3 form-group">
                                        <label for="deadline">Deadline</label>
                                        <input value="<?=htmlspecialchars($deadline);?>" type="date" class="form-control" name="deadline" id="deadline">
                                        <?php if (isset($errors['deadline'])): ?>
                                            <p class="mt-3 alert alert-danger"><?=htmlspecialchars($errors['deadline']);?></p>
                                        <?php endif; ?>
                                    </div>
                                    <div class="mb-3 form-group">
                                        <label for="priority">Priorité</label>
                                        <select name="priority" class="form-control" id="priority">
                                            <?php foreach ($priorities as $p): ?>
                                                <?php $selected = $priority == $p['id'] ? 'selected' : ''; ?>
                                                <option <?=$selected;?> value="<?=intval($p['id'])?>"><?=htmlspecialchars($p['label'])?></option>
                                            <?php endforeach; ?>
                                        </select>
                                        <?php if (isset($errors['priority'])): ?>
                                            <p class="mt-3 alert alert-danger"><?=htmlspecialchars($errors['priority']);?></p>
                                        <?php endif; ?>
                                    </div>
                                    <div class="form-group">
                                        <input class="btn btn-primary mt-4" type="submit" value="Enregistrer">
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

</html>