<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
</head>

<body>
    <section class="vh-100 gradient-custom-2">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-12 col-xl-10">
                    <div class="mask-custom">
                        <div class="card-body p-4 text-white">
                        <div class="text-center pt-3 pb-2">
                            <img src="img/check.webp" alt="Check" width="60">
                            <h2 class="my-4">Task List</h2>
                        </div>

                        <div class="text-center pt-3 pb-4">
                            <a href="addTask.php" class="btn btn-primary">Nouvelle tâche</a>
                        </div>

                        <!-- Affichage du message flash le cas échéant -->
                        <?php if ($flashMessage): ?>
                            <div class="alert alert-success text-center pt-3 pb-4"><?=htmlspecialchars($flashMessage);?></div>
                        <?php endif; ?>

                        <table class="table text-white mb-0">
                            <thead>
                                <tr>
                                <th scope="col">Task</th>
                                <th scope="col">Priority</th>
                                <th scope="col">Status</th>
                                <th scope="col">Deadline</th>
                                <th scope="col">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($tasks as $task): ?>
                                    <tr class="fw-normal">
                                        <td class="align-middle">
                                            <span><?=htmlspecialchars($task['title']);?></span>
                                        </td>
                                        <td class="align-middle">
                                            <h6 class="mb-0">
                                                <span class="badge <?=getPriorityClass($task['priority_id']);?>">
                                                    <?=htmlspecialchars($task['priority']);?>
                                                </span>
                                            </h6>
                                        </td>
                                        <td class="align-middle">
                                            <span><?=getTaskStatus($task);?></span>
                                        </td>
                                        <td class="align-middle">
                                            <span><?=dateFormat($task['deadline'])?></span>
                                        </td>
                                        <td class="align-middle">
                                            <a href="#!" data-mdb-toggle="tooltip" title="Done"><i class="fas fa-check fa-lg text-success me-3"></i></a>
                                            <a href="#!" data-mdb-toggle="tooltip" title="Remove"><i class="fas fa-trash-alt fa-lg text-warning"></i></a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

</html>